apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollouts-demo
spec:
  destination:
    name: ''
    namespace: rollouts-demo
    server: 'https://kubernetes.default.svc'
  source:
    path: dev
    repoURL: 'https://github.com/bilaldox/argo-project'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
